# Generated by Django 6.0.3 on 2026-03-17 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='clan',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='person',
            name='tribe',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name='FamilyUnion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('union_type', models.CharField(choices=[('customary', 'Customary Marriage'), ('civil', 'Civil Marriage'), ('religious', 'Religious Marriage'), ('informal', 'Informal Union')], default='customary', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('partners', models.ManyToManyField(related_name='unions', to='family.person')),
            ],
        ),
        migrations.CreateModel(
            name='ParentChild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parents', to='family.person')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='family.person')),
            ],
            options={
                'unique_together': {('parent', 'child')},
            },
        ),
        migrations.DeleteModel(
            name='Relationship',
        ),
    ]
