# Generated by Django 6.0.3 on 2026-03-17 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0002_person_clan_person_tribe_familyunion_parentchild_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='date_of_death',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='is_alive',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='person',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='person_photos/'),
        ),
    ]
